### ISSUE TITLE
MarioKart64: _reset() needs to support mid-race calls

### ISSUE THREAD

**Issue by bzier** [bzier/gym-mupen64plus#1]
Currently the MarioKart64 environment only supports calling `reset()` at the end of an episode (i.e. end of the race). It needs to support the ability to reset the environment mid-race. It should pause the game, navigate the menu to select 'retry', and wait for the race to be ready.

Implementing this will require modifications to `mupen64plus-input-bot` as it doesn't currently support the 'START' button (or a few others).

**Comment by kevinhughes27** [comment]
I suspect this project will bring to light many of the short comings of `mupen64plus-input-bot` :p

**Comment by bzier** [comment]
The input driver has now been [updated](https://github.com/kevinhughes27/mupen64plus-input-bot/pull/1) to support a more structured JSON response that allows for all of the controller buttons which should allow this issue to move forward.
