### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by bzier** [bzier/gym-mupen64plus#10]
There are likely many areas that could be optimized to improve performance. Some research needs to be done to determine the current bottlenecks.

A couple things that come to mind:
- There are currently two places in the controller server that are sleeping for 50ms. Previously it was simply a `pass` statement. This change was made to reduce CPU usage, but it may not be necessary. The value can be tweaked [here](https://github.com/bzier/gym-mupen64plus/blob/c51ca412d2548c447b7a0c62a29bcd76984d7523/gym_mupen64plus/envs/mupen64plus_env.py#L42).
- The screenshot code has always been a bottleneck on my machine. One thought I have that could improve this is #9.

*Based on feedback [here](https://github.com/kevinhughes27/TensorKart/issues/12#issuecomment-287570128).*

**Comment by bzier** [comment]
The 50ms sleep was definitely slowing things down. However, changing it back to `pass` was unbearable for the CPU. Reducing the sleep to 1ms seems to keep the CPU happy and greatly improve performance. I'm leaving this issue open for now because I'm sure there are other areas that can be improved upon as well.

**Comment by scientist1642** [comment]
Hi,
Just curious, what is the maximum frame/s one can currently get?

**Comment by bzier** [comment]
Hey @scientist1642,

I'm sorry I never saw your comment on this issue back in April. It is really hard to say what the max framerate is. That is likely hardware dependent. I have an 11+ year old system that runs painfully slow. Sometimes even just running the emulator (without any AI stuff) can hammer my CPU and drop in framerate. However, a capable system may be able to run the game and an AI agent, or even multiple worker threads simultaneously with CPU to spare, especially if running AI processing on a GPU for example (unfortunately I don't have a fancy new system to prove that).

One option I've seen that the mupen64plus emulator provides is a switch for `--nospeedlimit`, which their [documentation](https://mupen64plus.org/wiki/index.php?title=UIConsoleUsage) says will '*disable core speed limiter*'. On my system, this doesn't seem to have an effect most of the time (although I seem to recall playing with it a long time ago and seeing it run at super-speed). With more performance tuning, my hope is that using this switch may allow a reinforcement learning agent to run at speeds beyond real-time to reduce overall training time.

I know that doesn't really answer your question, so I apologize that after months of no response, I still haven't given you a good one ;) Hopefully that information helps though...

**Comment by scientist1642** [comment]
Thanks @bzier  for getting in touch!
I don't currently use a NES emulator but might get back to it sometime in the future. 
Many NES emulators I tried just ran too slowly compared to Atari environment (ALE) and took too much cpu power. 
Anyway if I test this one, I'll report the performance here.

**Comment by bzier** [comment]
Some improvements to performance were included in PR #38. Since performance can always continue to be improved, I'm going to close this issue. As additional performance-related issues come up, I will create more specific issues to address them individually, rather than having this issue perpetually open as a catch-all.
