### ISSUE TITLE
Video and rsp plugins not detected automatically

### ISSUE THREAD

**Issue by millerda** [bzier/gym-mupen64plus#13]
When I run the TensorKart play.py, the emulator was unable to launch due to undetected video and rsp plugins. In my fork I have a solution for this (basically specifying in the config.yml the paths and then modifying the mupen64plus call to use these plugins explicitly). Interested in a PR for this?

Link to related issue on the TensorKart repo: [https://github.com/kevinhughes27/TensorKart/issues/34](https://github.com/kevinhughes27/TensorKart/issues/34)

**Comment by kevinhughes27** [comment]
Adding config sounds like a fine solution but I'm more curious why your emulator didn't detect these in the first place. How did you install mupen64plus? If you run it without the gym does it work?

**Comment by bzier** [comment]
I agree with Kevin. The reason I hadn't added those to the config file is because we're not using any custom video or RSP plugins. I think it's fine for us to specify them, especially if it is a problem for others, but I too am curious why it won't run on its own. You should be able to run `mupen64plus ROMFile.n64` and just have it work out-of-the-box. One thing I did notice though is that it seems to 'cache' the last set of plugins you used. For example, if you run it specifying the custom input plugin, and then run the plain command, it seems to still run with that custom input plugin. I don't know if that's just on my machine, or some setting somewhere, but worth noting.

**Comment by millerda** [comment]
@kevinhughes27: I installed using `apt install mupen64plus`. Just running it from the command line did work originally, but I started using mupen64plus-qt to manage the plugins shortly after installing.

The issue might be that my plugins were installed in a different directory than specified in the gym environment for the input-bot (/usr/lib/x86_64-linux-gnu/mupen64plus/). I moved the input-bot driver to that needed for the gym environment (but not the other plugins), and maybe this caused mupen64plus to only look in that directory. It does run now without specifying the video and rsp plugins (command line and through the gym environment) for what it is worth.

Interestingly though if I respecify my original plugin install directory for only the input-bot it does not pick up the other plugins in that folder (probably due to the cacheing that @bzier mentioned).

I'm okay with leaving it as is since it is working for me now (and very possible that the issue was due to something I did), but having the arguments specified might prevent the same issue for someone else.

**Comment by kevinhughes27** [comment]
I think specifying this will make things more brittle. I am good to close this issue down I just have one question - how was the error message from the gym when it didn't load? As long as the error from mupen64plus was exposed properly we should be good.

**Comment by millerda** [comment]
When it wasn't working, the following was included in the output:

```
Core Warning: No video plugin attached.  There will be no video output.
Core Warning: No RSP plugin attached.  The video output will be corrupted.
```

**Comment by kevinhughes27** [comment]
And that wasn't too buried in other output?

**Comment by millerda** [comment]
It was somewhat buried, but if you're paying close attention as the emulator starts up it is noticeable.

**Comment by kevinhughes27** [comment]
@bzier you'll have to close or give me permission to do so :)

**Comment by millerda** [comment]
No problem
