### ISSUE TITLE
some errors with xvfb

### ISSUE THREAD

**Issue by liber145** [bzier/gym-mupen64plus#16]
This work is cool! I am trying to train a bot mario on my computer.
Since I do not have a graphic card, I comment 
```python
# cmd = [config['VGLRUN_CMD']] + cmd
```
in `mupen64plus_env.py`. I think `vglrun` is doing something to get graphic card rendering. 
Then with the default setting `USE_XVFB: true` and run a modified example code on my laptop.
```python
#!/bin/python
import gym, gym_mupen64plus
import numpy

env = gym.make('Mario-Kart-Luigi-Raceway-v0')
env.reset()
env.render()

for i in range(88):
    (obs, rew, end, info) = env.step([0, 0, 0, 0, 0]) # NOOP until green light
#    env.render()

for i in range(100):
    (obs, rew, end, info) = env.step([0, 0, 1, 0, 0]) # Drive straight
#    env.render()
    print i
    print np.sum(obs)

raw_input("Press <enter> to exit... ")

env.close()
```
It runs ok and prints 'i' as expected. However, I still get a window with a fixed image. I expect that there is no window coming out.

I plan to run it on a headless server. So I use xvfb to start a new virtual display by
```bash
$ Xvfb :3 -screen 0 640x480x16 &
$ export DISPLAY=unix:3.0
```
And run the example code above. This time I get stuck at 
```bash
('Frame ', '232', ': ', '[0, 0, 1, 0, 0]')
Reset called!

```
I hang here. Nothing comes out so far.

My expectation is to get it run on a headless server. I am quite newbie to these display tools, xvfb, vglrun, and so on. Could you help me? Any ideas are appreciated.

**Comment by bzier** [comment]
Hey @liber145,
Sorry you're having some trouble with getting up and running. I'm not really an expert with the virtual display stuff either, but did have to fight through a few things to get this working. I'll take a closer look in the next couple days and see what I can come up with for suggestions. Keep me updated if you make any progress in the meantime.

**Comment by liber145** [comment]
Thanks, @bzier! I will go on seeing it and let you know the progress.

**Comment by liber145** [comment]
@bzier I solve one problem and get two problems.
In my case, it takes me a long time to discover that I also need to comment `env.render()` under `env.reset()`. Then it worked as expected. 

The new problem:
1. Looking closer into xvfb. I can run the program in a virtual display by `xvfb-run -a -s "-screen 0 640x480x24" -- python example.py`, as `gym` suggested. 
Therefore, I do not need to comment `env.render()`. However, things got stuck there. 

2. The specific display can be given to [line142](https://github.com/bzier/gym-mupen64plus/blob/master/gym_mupen64plus/envs/mupen64plus_env.py#L142)  in `mupen64plus_env.py`. 
```python
import pyglet
dispname = ':3'
disp = pyglet.canvas.Display(dispname)
if self.viewer is None:
    self.viewer = rendering.SimpleImageViewer(display=disp)
```
I created 'Xvfb :3 -screen 0 640x480x24' and export it outside. It got stuck. But if `dispname=':0'`, which is the default display showing real images, it worked. 
Maybe something happens with subprocess. (It is just my guess. I am more newbie to multiple processes.)

Well, these two new problems did not bother me yet.

**Comment by bzier** [comment]
Great, I'm glad to hear you are making progress. I have been busy the last couple days and probably won't get the chance to look closely at any of this until later in the week or this weekend. At first glance it looks like you've made some other changes to the render code to use pyglet. I am not sure how that interacts with the XVFB virtual display. Originally I was just running the emulator (mupen64plus) in the virtual display, but it sounds like you may be attempting to run the whole environment in it. That may work too, but I honestly haven't tried it.

**Comment by liber145** [comment]
Yeah. That's exactly what I want to do since there is no display device in the server computer. [Gym](https://github.com/openai/gym/) environment uses `pyglet` in their [rendering](https://github.com/openai/gym/blob/master/gym/envs/classic_control/rendering.py#L321). So I used it here. 

Anyway, the original problem could be solved by commenting `env.render()`. I do not have a screen, so why I have to render it. :) Thanks for your quick response! I think we can close this issue. If you get the whole environment running in the virtual display, please let me know. Even though I can't make it work, I am curious about it~
