### ISSUE TITLE
trained model: straight line

### ISSUE THREAD

**Issue by ne0hit** [bzier/gym-mupen64plus#43]
Hello Brian, 

I was trying run the trained model and I thought that maybe the player was going in straight line due to lack of training nevertheless after generating the model with samples for around 6 races the behavior is still the same, any ideas about what the issue might be? For example the easiest track is Luigis racetrack and as soon as the player gets to the first curve the model is not reacting as expeted I think. I am not seeing the values between -80 and 80. Is worth to mention that I did double check the Joystick samples and those are ok going from -1 to 1 according to the record.py file.

Best Regards!

**Comment by bzier** [comment]
Hey @ne0hit, this sounds to me like it is more related to TensorKart rather than the gym environment itself (possibly related to recording, training, or playing). Can you open, copy/paste the issue over there? Thanks.

**Comment by bzier** [comment]
Linking the issue in the other repository for anyone else who stumbles onto this one:
https://github.com/kevinhughes27/TensorKart/issues/61
