### ISSUE TITLE
make all error and python version.

### ISSUE THREAD

**Issue by tanakataiki** [bzier/gym-mupen64plus#50]
Hello, thanks  for a great project.
I have 2 question about make all error and python version

1.  I have error below when input command  make all in terminal just the same as 
readme
( )=translationfrom Japanese

taiki@taiki:~/TensorKart/gym-mupen64plus/mupen64plus-src/mupen64plus-input-bot$ make all
    CC  _obj/src/plugin.o
    CC  _obj/src/controller.o
src/controller.c:17:18: fatal error: json.h: そのようなファイルやディレクトリはありません(No such ile or directory)
compilation terminated.
Makefile:250: ターゲット(target) '_obj/src/controller.o' のレシピで失敗しました(failed at this recipe)
make: *** [_obj/src/controller.o] エラー 1(error1)

Could you please tell me how to fix this issue,or Am I missing something?

2. I  read commits of Tensorkart and it says currently support python 3, 
https://github.com/kevinhughes27/TensorKart/commit/7014d1002c0b11816277a2c64674e77dff2463b7

to but this repositry supports python 2.7. So isnt it a problem?
I use python 3.5 version by the way.

thanks.

**Comment by bzier** [comment]
For the first issue, you probably need to install the json c library development packages. See the readme for that input plugin repo [here](https://github.com/kevinhughes27/mupen64plus-input-bot/blob/master/README.md#building). I'm not sure what OS you're using, but if it is Ubuntu (or similar), it should be the packages:

```
libjson-c2
libjson-c-dev
```

As for the second question, you are correct that this repo currently supports python 2.7. I haven't tried using python 3.5 recently; however, I don't think there is anything fundamental that would prevent using it. There may be a few minor syntax changes required, but I don't think it would be significant to update it. That isn't really on my to-do list at the moment, but if you'd like to try it, feel free to submit a pull request with any required changes. It may also just work as-is with python 3. If so, let me know and I'll update the readme to reflect that either version is fine.

**Comment by tanakataiki** [comment]
Thank you very much for your help. 
Sorry, I am a bit new to linux.
My enviroment is Ubuntu16.04LTS so it's the same.
I went there and cloned sdl below in input bot folder
https://github.com/mupen64plus/mupen64plus-input-sdl

It's written" It includes flags to link libjson-c, which it assumes has been installed into /usr/lib and /usr/include"
I try to find libjson-c2, libjson-c-dev in git page and libjson-c  in usr/lib but I couldnt find it.
1. Where can I find it or by command line?

thanks

**Comment by bzier** [comment]
No problem. Those are both packages that you can install using the built-in package manager, apt-get, in Ubuntu. See [here](https://help.ubuntu.com/community/AptGet/Howto) for an overview of how to use it if you are unfamiliar.

The command should be:
`apt-get install libjson-c2 libjson-c-dev`

Typically systems are configured where only the root user (super user / administrator) is allowed to manage packages. In this case you will likely get an error running the command, but can elevate your privileges with the term `sudo` (super user do):
`sudo apt-get install libjson-c2 libjson-c-dev`

The terminal will prompt you for your root user password. Once those two packages are installed, try the build again.

**Comment by tanakataiki** [comment]
Thank you very much I finally managed to compile it.
