### ISSUE TITLE
Add support for Glide64 video plugin

### ISSUE THREAD

**Issue by bzier** [bzier/gym-mupen64plus#53]
An accidental initial experiment is showing an approximate 21% performance increase using the Glide64 video plugin (`--gfx mupen64plus-video-glide64`) instead of the default Rice plugin (`--gfx mupen64plus-video-rice`). Need to do some more testing around this and then add support for it (ideally utilizing configuration to allow both). 

The problems I've seen in Mario Kart:
- reward/progress detection
- end episode detection

\* both are pixel-based operations

Note to self:
It appears that specifying `--gfx mupen64plus-video-glide64` actually results in the '*Glide64mk2 Video Plugin*' being loaded. I'm not sure if this is a naming thing, or if it is actually using the other, but there are apparently two different versions of the plugin ([glide64mk2](https://github.com/mupen64plus/mupen64plus-video-glide64mk2) & [glide64](https://github.com/mupen64plus/mupen64plus-video-glide64)).

**Comment by kevinhughes27** [comment]
Interesting. I never played with different video plugins on mupen64plus since the default always ran fast enough on my machines. I did play around with dolphon emu for gamecube and wii quite a bit back in the day and there were big differences in performance sometimes. I seem to recall it was game specific and there was a list of which plugin to use for each game (this might not be the case anymore I haven't kept up with it). All that to say that this probably does make sense to offer as a configuration option.

If I recall the episode detection was pretty brittle and pixel based. The rendering must be slightly different and causing it to break. If you look into it let me know what you find and we can figure out a smarter computer vision ish solution. We probably just need to use a relative pattern vs absolute one.

**Comment by bzier** [comment]
Yes, that is still true (brittle and pixel-based). The current end detection is looking at one particular pixel and ensuring it's color is a specific value. Basically, after making changes to the reward system, which tracks the colored progress rectangle around the edges of the screen, the HUD view only shows that rectangle. It does not show the lap numbers any more. Except as soon as you cross the finish line, when the viewing angle changes, the lap numbers show back up. As soon as the particular pixel in the 3 turns the appropriate color, that's the end of the episode. It seems that the other video plugin either renders it slightly out of position, or with a slightly different color, or something. Hence: brittle. I'd like it if I had a more robust way of tracking progress and detecting the end, but at the moment, the solution I'm using was just to sample that single pixel (which works great for the original video plugin).

---
## Throughout the race, no lap numbers are shown:
![Throughout](https://user-images.githubusercontent.com/714528/39458429-3f3040ac-4ca9-11e8-862c-5814e9bf578a.png)
---
## After the race, the lap numbers re-appear and a pixel in the first 3 is sampled to determine it's appearance:
![After](https://user-images.githubusercontent.com/714528/39458430-3f4b3fa6-4ca9-11e8-8ca2-cf017cc7a67e.png)
---

**Comment by bzier** [comment]
Here's the difference between Rice and Glide64 at the end of the race. You can see a significant difference in the way the plugin processed the stuff on the screen. Rice is quite a bit more smooth/blurry, whereas the Glide64 shot seems to be more aliased. You can definitely see that the lap number 3 is rendered differently enough that looking for the color of a specific pixel will obviously break.

![ee](https://user-images.githubusercontent.com/714528/39458867-acf5668c-4cac-11e8-984b-3d27dff3278d.gif)

**Comment by bzier** [comment]
I think the reward detection is off too, unsurprisingly. I edited the original issue to reflect that as well.

**Comment by kevinhughes27** [comment]
Oh yeah there is a difference there for sure!

**Comment by bzier** [comment]
I discovered that I can actually run both Glide64 and Glide64mk2. It appears that specifying a plugin name will attempt to match a plugin by name. Specifying `mupen64plus-video-glide64` was matching `mupen64plus-video-glide64mk2.so`. If I specify the 'full' name as `mupen64plus-video-glide64.so` with the `.so` extension, it properly loads Glide64. Here are the current reward values for the two hard-coded races I have at the moment:
```yml
"Luigi Raceway"
      Rice: 3807.3
Glide64mk2: 3807.9
   Glide64: 3588.3

"Mario Raceway"
      Rice: 4390.8
Glide64mk2: 4390.2
   Glide64: 4213.2
```
Still need to look into the discrepancy in the values. Why do they differ when the action sequence and progression through the race is the same?

**Comment by bzier** [comment]
Created a new separate issue to address the reward function differences. Closing this one, since different video plugins (including glide64) are supported, which was the purpose of this issue.
