### ISSUE TITLE
Dependencies for building the input bot

### ISSUE THREAD

**Issue by Mr-Pepe** [bzier/gym-mupen64plus#54]
What do you think about adding
sudo apt-get install libjson-c-dev libjson-c2
to the readme for installing the input bot? 
The errors that pop up if the packages are not installed were not immediately obvious to me.
I know it's clearly stated in the input bot repo that those packages need to be installed, but maybe the addition could help beginners like me to get going with this awesome project.

**Comment by bzier** [comment]
Yes, I think that's a great idea. I think I wrote that section of the README before we updated the input bot to use a JSON format. Never went back to update this README after that. Thanks for the suggestion.

**Comment by bzier** [comment]
I'll try to take care of that soon, maybe tonight if I get to it.

**Comment by bzier** [comment]
@Mr-Pepe I updated the README as you suggested and added a note reflecting that the current instructions may have changed and linked to the repo for that project. Hopefully that helps other future newcomers.

**Comment by Mr-Pepe** [comment]
Nice, I like it. I am new to all this, but next time I will just fix it and create a Pull Request to save you time.

**Comment by bzier** [comment]
Thanks. If you have any other questions, or tougher problems than updating the README ;) feel free to open additional issues. I'll do my best to respond quickly (usually within a couple days).
