### ISSUE TITLE
Update outdated README

### ISSUE THREAD

**Issue by bzier** [bzier/gym-mupen64plus#56]
The README documentation has fallen a bit behind implementation (go figure). Need to take a couple passes through and update the areas which are no longer accurate. It may also be worth adding additional information and splitting into multiple files for better organization.

**Comment by bzier** [comment]
I'm thinking it might make sense to utilize the GitHub Wiki pages for all of the content that I have. The README file is too long and cumbersome to navigate or scroll through. It would be nice to break it into different pages with navigation. The downside is that it separates the documentation from the code, but it seems like it may be easier to maintain than manually managing links between a bunch of markdown files in the repository.

**Comment by kevinhughes27** [comment]
Something I've seen done before is to start the readme with a table of contents. GitHub markdown  supports linking to titles. I can find an example if you want

**Comment by bzier** [comment]
Yeah, I may go with that approach. It sounded like the Wiki navigation sidebar automatically populates with the list of pages, whereas, a markdown TOC would need to be maintained manually. New pages/sections would need to be added, renamed sections would need to be updated, etc. I'm on the fence about which way I want to go with it. Thanks for the input.

**Comment by bzier** [comment]
The README has been updated quite a bit over the last (almost) 3 years. The setup instructions have been simplified with the Docker implementation. Old setup split to a new file. The architecture, and new threading documentation have been split into new files as well. For now, I think the issues I was concerned about in this issue have been addressed. I may continue to tweak and improve the documentation, but I don't think I need this issue for it. Marking it closed.
